import { BaseEntity } from './BaseEntity';

/**
 * Patient - Represents a patient record within a nurse's shift
 *
 * Core entity for bedside care tracking. Created when nurse starts
 * attending to a patient during their shift. All clinical notes,
 * recordings, and transcriptions reference a patient.
 *
 * Lifecycle:
 * 1. Created when nurse adds a new patient (Dashboard)
 * 2. Updated throughout shift as AI extracts clinical data
 * 3. Automatically deleted when shift ends (session_id cleanup)
 *
 * Privacy & Data Retention:
 * - PHI (Protected Health Information) is stored locally only
 * - Automatically purged on shift end (expires_at = session.ended_at)
 * - No backend sync in v1 (future feature requires HIPAA compliance)
 */

/**
 * Patient status within the shift
 */
export enum PatientStatus {
  /**
   * Currently being attended to
   */
  ACTIVE = 'active',

  /**
   * Care completed but still in shift context
   */
  COMPLETED = 'completed',

  /**
   * Discharged from care
   */
  DISCHARGED = 'discharged',

  /**
   * Transferred to another unit/facility
   */
  TRANSFERRED = 'transferred',
}

/**
 * Patient entity representing a person receiving care.
 * Extends BaseEntity with patient-specific fields.
 */
export interface Patient extends BaseEntity {
  /**
   * Patient's full name.
   * HIPAA consideration: This is PHI and must be handled securely.
   *
   * @example "John Smith"
   */
  name: string;

  /**
   * Medical Record Number or hospital patient identifier.
   * Format varies by institution.
   * Optional - may not be available in emergency scenarios.
   *
   * @example "MRN-123456" | "A12345678"
   */
  mrn: string | null;

  /**
   * Bed assignment or room number.
   * Used for visual organization in Dashboard bed cards.
   *
   * @example "301-A" | "ICU-12" | "ER-3"
   */
  bed: string | null;

  /**
   * Date of birth (ISO 8601 date string).
   * Used for age calculation and patient identification.
   *
   * @example "1965-07-15"
   */
  date_of_birth: string | null;

  /**
   * Current status of the patient within this shift.
   */
  status: PatientStatus;

  /**
   * Primary diagnosis or chief complaint.
   * AI-extracted from transcriptions or manually entered.
   *
   * @example "Pneumonia" | "Post-operative care" | "CHF exacerbation"
   */
  diagnosis: string | null;

  /**
   * Known allergies (comma-separated or structured).
   * AI-extracted from bedside conversations.
   * Critical safety information.
   *
   * @example "Penicillin, Latex" | "NKDA" (No Known Drug Allergies)
   */
  allergies: string | null;

  /**
   * Current medications (structured or free text).
   * AI-extracted from transcriptions.
   *
   * Future: Migrate to separate Medication[] entity for structured data.
   *
   * @example "Lisinopril 10mg PO daily, Metformin 500mg PO BID"
   */
  medications: string | null;

  /**
   * Additional clinical notes or context.
   * Free-form text for nurse observations not captured elsewhere.
   */
  notes: string | null;

  /**
   * Timestamp of last interaction with this patient (ISO 8601 format).
   * Updated whenever:
   * - New recording is made
   * - Clinical data is extracted
   * - Manual edits are made
   *
   * Used for sorting patients by recency in Dashboard.
   *
   * @example "2026-03-25T14:30:22.123Z"
   */
  last_interaction_at: string;

  /**
   * Total number of clinical notes associated with this patient.
   * Incremented when new note is created.
   * Used for patient detail summary.
   */
  note_count: number;

  /**
   * Total number of audio recordings for this patient.
   * Used for storage tracking and patient detail summary.
   */
  recording_count: number;
}

/**
 * Type for creating a new patient (before persistence).
 * Omits fields that are auto-generated by the repository.
 */
export type CreatePatientInput = Omit<
  Patient,
  | 'id'
  | 'created_at'
  | 'expires_at'
  | 'last_interaction_at'
  | 'note_count'
  | 'recording_count'
> & {
  session_id: string;
  name: string;
  status: PatientStatus;
};

/**
 * Type for updating an existing patient.
 * Allows partial updates to mutable fields.
 */
export type UpdatePatientInput = Partial<
  Pick<
    Patient,
    | 'name'
    | 'mrn'
    | 'bed'
    | 'date_of_birth'
    | 'status'
    | 'diagnosis'
    | 'allergies'
    | 'medications'
    | 'notes'
    | 'last_interaction_at'
    | 'note_count'
    | 'recording_count'
  >
>;
