import { BaseEntity } from './BaseEntity';

/**
 * Session - Represents a nurse's work shift
 *
 * Core entity for tracking shift lifecycle and data isolation.
 * All patient data, recordings, and notes are associated with a session.
 *
 * Lifecycle:
 * 1. Created when nurse starts shift (ModeSelectionScreen)
 * 2. Active during entire shift (referenced by all created entities)
 * 3. Ended when nurse taps "End Shift" (Dashboard)
 * 4. Purged 30 days after ended_at (cleanup policy)
 */

/**
 * Session status enum
 */
export enum SessionStatus {
  /**
   * Shift is currently active (nurse is working)
   */
  ACTIVE = 'active',

  /**
   * Shift has ended but data not yet purged
   */
  ENDED = 'ended',

  /**
   * Shift ended with incomplete sync (offline scenarios)
   */
  PENDING_SYNC = 'pending_sync',
}

/**
 * Session entity representing a nurse's work shift.
 * Extends BaseEntity with shift-specific fields.
 */
export interface Session extends BaseEntity {
  /**
   * Display name of the nurse conducting the shift.
   * Entered on ModeSelectionScreen before starting shift.
   *
   * @example "Julia Martinez"
   */
  nurse_name: string;

  /**
   * Timestamp when the shift started (ISO 8601 format).
   * Set when nurse taps "Start working!" button.
   *
   * @example "2026-03-25T08:00:00.000Z"
   */
  started_at: string;

  /**
   * Timestamp when the shift ended (ISO 8601 format).
   * Set when nurse taps "End Shift" button.
   * Null if shift is still active.
   *
   * @example "2026-03-25T16:00:00.000Z"
   */
  ended_at: string | null;

  /**
   * Current status of the session.
   * Drives UI state and cleanup behavior.
   */
  status: SessionStatus;

  /**
   * Device identifier where the shift is running.
   * Used for multi-device scenarios and audit logs.
   *
   * Format: Platform-specific device ID or generated UUID
   * @example "android_device_abc123" | "web_session_xyz789"
   */
  device_id: string;

  /**
   * App version when session was created.
   * Critical for data migration and debugging.
   *
   * @example "1.0.0" | "1.2.3-beta"
   */
  app_version: string;

  /**
   * Total number of patients seen during this shift.
   * Incremented when new patient is created.
   * Used for shift summary statistics.
   */
  patient_count: number;

  /**
   * Total duration of audio recordings in seconds.
   * Used for usage analytics and storage management.
   */
  total_recording_duration: number;

  /**
   * Backend sync status (for future API integration).
   * Tracks whether session data has been uploaded to server.
   */
  synced: boolean;

  /**
   * Timestamp of last successful sync (ISO 8601 format).
   * Null if never synced.
   *
   * @example "2026-03-25T16:05:00.000Z"
   */
  last_synced_at: string | null;
}

/**
 * Type for creating a new session (before persistence).
 * Omits fields that are auto-generated by the repository.
 */
export type CreateSessionInput = Omit<
  Session,
  | 'id'
  | 'created_at'
  | 'expires_at'
  | 'session_id'
  | 'ended_at'
  | 'patient_count'
  | 'total_recording_duration'
  | 'synced'
  | 'last_synced_at'
> & {
  nurse_name: string;
  started_at: string;
  status: SessionStatus.ACTIVE;
  device_id: string;
  app_version: string;
};

/**
 * Type for updating an existing session.
 * Allows partial updates to mutable fields.
 */
export type UpdateSessionInput = Partial<
  Pick<
    Session,
    | 'ended_at'
    | 'status'
    | 'patient_count'
    | 'total_recording_duration'
    | 'synced'
    | 'last_synced_at'
  >
>;
