import { BaseEntity } from './BaseEntity';

/**
 * Transcription - Speech-to-text output from audio recordings
 *
 * Represents the raw transcribed text from an audio recording.
 * Generated by TranscriptionService (Whisper OpenVino API).
 * Serves as input for AI clinical data extraction.
 *
 * Lifecycle:
 * 1. Created when audio recording is uploaded to transcription API
 * 2. Processing state transitions (pending → processing → completed/failed)
 * 3. Used by AIExtractionService to generate ClinicalNotes
 * 4. Purged when parent session ends (same as audio recording)
 *
 * Design Notes:
 * - Supports real-time streaming transcription (word-by-word updates)
 * - Stores raw text + timestamps for word-level alignment
 * - Tracks processing state for retry logic and error handling
 */

/**
 * Transcription processing status
 */
export enum TranscriptionStatus {
  /**
   * Queued for transcription (not yet sent to API)
   */
  PENDING = 'pending',

  /**
   * Currently being processed by transcription service
   */
  PROCESSING = 'processing',

  /**
   * Transcription completed successfully
   */
  COMPLETED = 'completed',

  /**
   * Transcription failed (API error, timeout, invalid audio)
   */
  FAILED = 'failed',

  /**
   * Partial transcription available (streaming in progress)
   */
  PARTIAL = 'partial',
}

/**
 * Word-level timestamp for precise alignment
 */
export interface WordTimestamp {
  /**
   * The transcribed word
   * @example "patient"
   */
  word: string;

  /**
   * Start time in seconds from recording start
   * @example 12.34
   */
  start: number;

  /**
   * End time in seconds from recording start
   * @example 12.78
   */
  end: number;

  /**
   * Confidence score for this word (0-1 scale)
   * @example 0.95
   */
  confidence: number;
}

/**
 * Transcription entity representing speech-to-text output.
 * Extends BaseEntity with transcription-specific fields.
 */
export interface Transcription extends BaseEntity {
  /**
   * Reference to the audio recording this transcription is from.
   * Foreign key to AudioRecording.id
   */
  audio_recording_id: string;

  /**
   * Reference to the patient being discussed in the audio.
   * Foreign key to Patient.id
   * Null if patient context hasn't been determined yet.
   */
  patient_id: string | null;

  /**
   * Current processing status of the transcription.
   */
  status: TranscriptionStatus;

  /**
   * Full transcribed text content.
   * Populated when status = COMPLETED or PARTIAL.
   *
   * @example "Patient reports chest pain radiating to left arm. Blood pressure 140 over 90. Heart rate 88. Administering aspirin 325 milligrams."
   */
  text: string;

  /**
   * Word-level timestamps for precise audio-text alignment.
   * Used for:
   * - Playback synchronization (highlight words as audio plays)
   * - Editing corrections (jump to audio timestamp)
   * - Confidence visualization (highlight low-confidence words)
   *
   * Empty array if word-level timestamps not available.
   */
  word_timestamps: WordTimestamp[];

  /**
   * Overall transcription confidence score (0-1 scale).
   * Average of all word-level confidence scores.
   * Null if transcription failed or pending.
   *
   * @example 0.87
   */
  confidence_score: number | null;

  /**
   * Language code detected/used for transcription.
   * ISO 639-1 format (2-letter code).
   *
   * @example "en" | "es" | "fr"
   */
  language: string;

  /**
   * Transcription API/service used.
   * Tracks which strategy was used for this transcription.
   *
   * @example "whisper-1" | "azure-stt" | "google-cloud-stt"
   */
  service_provider: string;

  /**
   * API request ID for tracking and debugging.
   * Provided by transcription service for support requests.
   *
   * @example "req_abc123xyz"
   */
  api_request_id: string | null;

  /**
   * Timestamp when transcription started (ISO 8601 format).
   * @example "2026-03-25T14:30:22.123Z"
   */
  started_at: string;

  /**
   * Timestamp when transcription completed (ISO 8601 format).
   * Null if still processing or failed.
   *
   * @example "2026-03-25T14:30:45.678Z"
   */
  completed_at: string | null;

  /**
   * Processing duration in milliseconds.
   * Used for performance tracking and billing estimates.
   *
   * @example 23555 (23.555 seconds)
   */
  processing_duration_ms: number | null;

  /**
   * Error message if transcription failed.
   * Null if successful or still processing.
   *
   * @example "Audio file too short" | "API rate limit exceeded" | "Unsupported audio format"
   */
  error_message: string | null;

  /**
   * Number of retry attempts if transcription failed.
   * Used for exponential backoff retry logic.
   */
  retry_count: number;

  /**
   * Whether this transcription has been used to generate clinical notes.
   * Used to track extraction pipeline progress.
   */
  extracted: boolean;

  /**
   * Timestamp when extraction completed (ISO 8601 format).
   * Null if not yet extracted.
   *
   * @example "2026-03-25T14:31:00.000Z"
   */
  extracted_at: string | null;
}

/**
 * Type for creating a new transcription (before persistence).
 * Omits fields that are auto-generated by the repository.
 */
export type CreateTranscriptionInput = Omit<
  Transcription,
  | 'id'
  | 'created_at'
  | 'expires_at'
  | 'text'
  | 'word_timestamps'
  | 'confidence_score'
  | 'completed_at'
  | 'processing_duration_ms'
  | 'error_message'
  | 'retry_count'
  | 'extracted'
  | 'extracted_at'
> & {
  session_id: string;
  audio_recording_id: string;
  status: TranscriptionStatus.PENDING;
  language: string;
  service_provider: string;
  started_at: string;
};

/**
 * Type for updating an existing transcription.
 * Allows partial updates to mutable fields.
 */
export type UpdateTranscriptionInput = Partial<
  Pick<
    Transcription,
    | 'patient_id'
    | 'status'
    | 'text'
    | 'word_timestamps'
    | 'confidence_score'
    | 'api_request_id'
    | 'completed_at'
    | 'processing_duration_ms'
    | 'error_message'
    | 'retry_count'
    | 'extracted'
    | 'extracted_at'
  >
>;
