/**
 * OfflineQueueDb
 *
 * Dexie.js service for the offline audio chunk queue.
 *
 * Database : 'offline_queue'
 * Store    : 'offline_queue'
 * — database and store names match what EndShiftService clears on shift end.
 *
 * Schema — offline_queue store:
 *   id           UUID primary key (generated by add())
 *   session_id   current shift — links to sessions table in sofia_db
 *   recording_id groups all chunks from one continuous recording
 *   patient_id   nullable — bed/patient association
 *   blob         raw audio Blob (WebM/Opus)
 *   mime_type    'audio/webm;codecs=opus'
 *   chunk_index  0-based sequence number within the recording
 *   size_bytes   blob.size — for upload monitoring
 *   created_at   ISO timestamp (set by add())
 *
 * Public API:
 *   add(chunk)              → Promise<ChunkRecord>     — persist a new chunk
 *   getBySession(sessionId) → Promise<ChunkRecord[]>   — ordered by chunk_index
 *   deleteById(id)          → Promise<void>            — remove after successful upload
 *   countBySession(sessionId) → Promise<number>        — pending count for a session
 */

import Dexie from 'dexie';
import { v4 as uuidv4 } from 'uuid';

const _db = new Dexie('offline_queue');

_db.version(1).stores({
    offline_queue:
        'id, session_id, recording_id, patient_id, chunk_index, created_at',
});

const OfflineQueueDb = {
    /**
     * Persist a new audio chunk.
     * Generates id and created_at automatically.
     *
     * @param {{ session_id, recording_id, patient_id, blob, mime_type, chunk_index, size_bytes }} chunk
     * @returns {Promise<object>} The stored record including generated id and created_at.
     */
    async add(chunk) {
        const record = {
            id: uuidv4(),
            created_at: new Date().toISOString(),
            ...chunk,
        };
        await _db.table('offline_queue').add(record);
        return record;
    },

    /**
     * Return all chunks for a session ordered by chunk_index (ascending).
     * Covers multiple recordings within the same shift.
     *
     * @param {string} sessionId
     * @returns {Promise<object[]>}
     */
    async getBySession(sessionId) {
        return _db
            .table('offline_queue')
            .where('session_id')
            .equals(sessionId)
            .sortBy('chunk_index');
    },

    /**
     * Delete a single chunk by its primary key.
     * Called after the chunk has been successfully uploaded to the API.
     *
     * @param {string} id
     * @returns {Promise<void>}
     */
    async deleteById(id) {
        await _db.table('offline_queue').delete(id);
    },

    /**
     * Count pending chunks for a session.
     * Useful for the flush-queue check in EndShiftService.
     *
     * @param {string} sessionId
     * @returns {Promise<number>}
     */
    async countBySession(sessionId) {
        return _db
            .table('offline_queue')
            .where('session_id')
            .equals(sessionId)
            .count();
    },
};

export default OfflineQueueDb;
